import { authRoles } from "./auth/authRoles";

export const navigations = (t) => {
  return [
    {
      name: t("SideNav.1"),
      description: "Lorem ipsum dolor sit.",
      type: "link",
      path: "/dashboard/v0",
      icon: "i-Home1",
      role: authRoles.Essentiel,
    },
    {
      name: t("SideNav.2"),
      description: "Lorem ipsum dolor sit.",
      type: "link",
      path: "/evaluation-bien",
      icon: "i-Money-Bag",
      role: authRoles.Essentiel,
    },
    {
      name: t("SideNav.3"),
      description: "Lorem ipsum dolor sit.",
      type: "link",
      path: "/mes-biens",
      icon: "i-Library",
      role: authRoles.Essentiel,
    },
    {
      name: "Prospecter",
      description: "Lorem ipsum dolor sit.",
      type: "link",
      path: "/newleads",
      icon: "i-Target",
      role: authRoles.Performance,
    },
    {
      name: t("SideNav.6"),
      description: "Lorem ipsum dolor sit.",
      type: "link",
      path: "/retains",
      icon: "i-retain",
      role: authRoles.Expert,
    },
    {
      name: t("SideNav.5"),
      description: "Lorem ipsum dolor sit.",
      type: "link",
      path: "/moncompte",
      icon: "i-Administrator",
      role: authRoles.Essentiel,
    },
    {
      name: "Data Tables",
      description: "Lorem ipsum dolor sit.",
      type: "dropDown",
      icon: "i-File-Horizontal-Text",
      sub: [
        {
          icon: "i-File-Horizontal-Text",
          name: "Basic",
          path: "/data-table/basic",
          type: "link",
        },
        {
          icon: "i-Full-View-Window",
          name: "Default Sorted",
          path: "/data-table/default-sorted",
          type: "link",
        },
        {
          icon: "i-Filter-2",
          name: "Multi Column Ordering",
          path: "/data-table/multi-column-ordering",
          type: "link",
        },
        {
          icon: "i-Code-Window",
          name: "Search in Table",
          path: "/data-table/search",
          type: "link",
        },
        {
          icon: "i-Filter-2",
          name: "Cell Editor",
          path: "/data-table/cell-editor",
          type: "link",
        },
      ],
    },
    {
      name: "Sessions",
      description: "Lorem ipsum dolor sit.",
      type: "dropDown",
      icon: "i-Administrator",
      sub: [
        {
          icon: "i-Add-User",
          name: "Sign up",
          path: "/sessions/signup",
          type: "link",
        },
        {
          icon: "i-Checked-User",
          name: "Sign in",
          path: "/sessions/signin",
          type: "link",
        },
        {
          icon: "i-Find-User",
          name: "Forgot",
          path: "/sessions/forgot",
          type: "link",
        },
      ],
    },
    {
      name: "Pages",
      description: "Lorem ipsum dolor sit.",
      type: "dropDown",
      icon: "i-Windows-2",
      sub: [
        {
          icon: "i-Error-404-Window",
          name: "Not Found",
          path: "/sessions/404",
          type: "link",
        },
        {
          icon: "i-Billing",
          name: "Pricing Table",
          path: "/pages/pricing-table",
          type: "link",
        },
        {
          icon: "i-File-Search",
          name: "Search Results",
          path: "/pages/search-results",
          type: "link",
        },
        {
          icon: "i-Administrator",
          name: "User Profile",
          path: "/pages/user-profile",
          type: "link",
        },
        {
          icon: "i-Speach-Bubble-Asking",
          name: "FAQ",
          path: "/pages/faq",
          type: "link",
        },
        {
          icon: "i-File",
          name: "Blank Page",
          path: "/pages/blank-page",
          type: "link",
        },
      ],
    },
    {
      name: "Icons",
      description: "600+ premium icons",
      type: "link",
      icon: "i-Cloud-Sun",
      path: "/icons",
    },
    {
      name: "Others",
      description: "Lorem ipsum dolor sit.",
      type: "dropDown",
      icon: "i-Double-Tap",
      sub: [
        {
          icon: "i-Error-404-Window",
          name: "Not found",
          path: "/others/404",
          type: "link",
        },
      ],
    },
    {
      name: "Doc",
      type: "extLink",
      description: "Lorem ipsum dolor sit.",
      tooltip: "Documentation",
      icon: "i-Safe-Box1",
      path: "http://demos.ui-lib.com/gull-doc",
    },
  ];
};
